# Generated by Django 2.1.3 on 2019-06-11 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AIWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('pi', models.TextField(default='unknown', verbose_name='source PI')),
                ('target', models.TextField(default='', verbose_name='csv content')),
            ],
        ),
    ]
